### ISSUE TITLE
Unreal 5 and Shared Spatial Anchors??

### ISSUE THREAD

**Issue by turkodamian2** [oculus-samples/Unreal-SharedAnchorsSample#3]
Hi, is it possible to use Unreal 5 with Shared Spatial Anchors for developing mixed reality experiences for Quest 3?

**Comment by turkodamian** [comment]
I could succesfully package and build this project with UE 5.3.2

**Comment by Nickauhla** [comment]
Hello mate,
It's me again.
Could you explain me how you made it work on Quest 3 ?
I've did the same thing than for the other SceneShareSample, but app immediatly crashes on launch.
